permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap
  
plugins:
 - jekyll-seo-tag

  
twitter: a_sarentorbic  
google_analytics: UA-150203379-1
comments: true
theme: minima
name: "Alex"
url: "https://aleksandar-b.github.io/blog"
description: Blog
