permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap
  
twitter: a_sarentorbic  
google_analytics: UA-150203379-1
theme: minima
name: "Alex"
url: "https://aleksandar-b.github.io/blog"
description: Blog
