permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Zach Holman
url: https://aleksandar-b.github.io
baseUrl: /blog
description: A fantastic blog that is fantastic.
twitter: holman
